node {
    stage('Build Fresh Image Sonarqube') {
        checkout scm
        def props = readProperties file: 'sonarqube/build.properties'
        sh "docker build --build-arg ALPINE_VERSION=${props.ALPINE_VERSION} \
                            --build-arg JAVA_VERSION=${props.JAVA_VERSION} \
                            --build-arg SONARQUBE_VERSION=${props.SONARQUBE_VERSION} \
                            -t sonarqube:${params.BUILDENV}-${props.SONARQUBE_VERSION} sonarqube"
        docker.withRegistry(props.MSR, props.MSRCREDS) {
            sh "docker push sonarqube:${params.BUILDENV}-${props.SONARQUBE_VERSION}"
        }
    }
}

